name: Java CI/CD & Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - uses: thecodemonkey/action-get-gradle-version@master
        id: getVersion
        with:
          file: ./build.gradle.kts

      - run: 'echo App Version Is ${{ steps.getVersion.outputs.version }}'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew build

      - name: Gradle Jar
        run: ./gradlew jar

      - name: Change Jar Name
        shell: bash
        run: |
          cp ./build/libs/AutoGraderDocsOpener-${{ steps.getVersion.outputs.version }}.jar ./build/libs/DocsOpener.jar

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ steps.getVersion.outputs.version }}
          tag: Release
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./build/libs/DocsOpener.jar

