name: Java CI/CD & Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - uses: thecodemonkey/action-get-gradle-version@master
        id: getVersion
        with:
          file: ./build.gradle.kts

      - run: 'echo App Version Is ${{ steps.getVersion.outputs.version }}'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew build

      - name: Gradle Jar
        run: ./gradlew jar

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.getVersion.outputs.version }}.${{ github.ref }}
          tag_name: ${{ steps.getVersion.outputs.version }}.${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/libs/AutoGraderDocsOpener-${{ steps.getVersion.outputs.version }}.jar
          asset_name: DocsOpener-${{ steps.getVersion.outputs.version }}.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"




#      - name: upload Jar to release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./build/libs/AutoGraderDocsOpener-${{ steps.getVersion.outputs.version }}.jar
#          asset_name: azblogfilter.linux-amd64.tar.gz
#          asset_content_type: application/
